### ISSUE TITLE
Bessel Function of the Second Kind

### ISSUE THREAD

**Issue by qoheniac** [At0micBee/scilib#18]
The following code does not terminate (or at least not in a reasonable time):
```rust
use scilib::math::bessel::y;

fn main() {
    println!("{}", y(0.0, 0.0));
}
```
The same happens for any other order and also if we pass `f64::INFINITY` as argument instead of `0.0`. I think it should return `Complex64 { re: f64::NAN, im: f64::NAN }` or panic. Actually, I think it should do that for any argument form negative infinity to zero (right now it returns the upper half-plane limit for negative arguments).

**Comment by At0micBee** [comment]
Hi,

I've found a way to avoid the infinite computation time for `y(0.0, 0)`, it now returns `NaN + NaN*i`, as it should.
About the results for `f64::INFINITY`, the value isn't right either, that's due to the current implementation of the function which becomes inaccurate for large values of `x`. That's been on the list of things I need to change for a while but I've been really busy lately, a proper patch for that will be coming.

I am unsure what you mean for negative `x` however, the values I'm getting are coherent with other calculator I know of, do you have any specific examples?

Cheers!

**Comment by qoheniac** [comment]
Here is an example for the ambiguity on the negative real axis:
```rust
use num_complex::Complex64;
use scilib::math::bessel::y;

fn main() {
    for im in [-1e-16, 0.0, 1e-16] {
        println!("{}", y(Complex64 { re: -1.0, im: im }, 0.0));
    }
}
```
This prints out:
```
0.08825714736669549-1.530390930741801i
0.08825714736669549+1.530390930741801i
0.08825714736669549+1.530390930741801i
```

**Comment by At0micBee** [comment]
Hi again,

That seems to be correct, when checking against both Wolfram Alpha, we have:
`bessely[0, -1 -1e-16i] vs bessely[0, -1] vs bessely[0, -1 +1e-16i]`
which outputs:
`{0.088257 - 1.5304 i, 0.088257 + 1.5304 i, 0.088257 + 1.5304 i}`

and Python using `scipy`:
```python
from scipy.special import yv

for im in [-1e-16, 0, 1e-16]:
    res = yv(0, -1 + im * 1j)
    print(res)
```
which yields:
```
(0.08825696421567691-1.5303953731159332j)
(0.088256964215677+1.5303953731159332j)
(0.08825696421567691+1.5303953731159332j)
```

This might be an unavoidable numerical error? If you have a reference to the version you're expecting I'll be happy to give it a read!

In any case, I'll try to work on a fix for the incorrect large values of the function, most likely basing a new approach on the Numerical Recipes solution to the problem.

Cheers!

**Comment by At0micBee** [comment]
Fixed incorrect value at `y(0,0)` or `y(f64::INFINITY, 0)` in 28bdeab .

**Comment by qoheniac** [comment]
The function has a branch cut there and is thus not well defined and IIRC GSL and Netlib's Cephes return a domain error there. But this was more of a side note of mine and I think it's not a problem and as you have shown it's consistent with other implementations. The real issue was the infinite computation for infinite arguments or zero and I'm glad you fixed that. Thanks a lot!
