### ISSUE TITLE
Use num::Complex 

### ISSUE THREAD

**Issue by JayKickliter** [At0micBee/scilib#9]
Using this library in another library can be difficult since it defines its own complex type. Since Rust doesn't have a `Complex<T>` it the standard library, [`num::Complex`](https://docs.rs/num/latest/num/struct.Complex.html) is the closest we have a to universal vocabulary type.

**Comment by At0micBee** [comment]
Hi,
True, I wanted to keep the library as monolithic as possible at first but I agree that it would offer better compatibility if using num-complex. I'll look into it in the near future.
Cheers!

**Comment by JayKickliter** [comment]
> I wanted to keep the library as monolithic as possible

I 100% understand. And I'm extra fine with it when it's not part of the public API.

**Comment by At0micBee** [comment]
Version 0.5.0 is live using `num_complex::Complex64` to replace the original Complex implementation.

All tests are passing, it should be all good!
